### ISSUE TITLE
Less stringent requirements?

### ISSUE THREAD

**Issue by ewels** [jsvine/spectra#12]
Many thanks for the recent update to add support for `networkx` 2.0!

I'm now playing around with the requirements for my MultiQC package which uses Spectra and ran into the following installation problem just earlier today:

```
error: networkx 2.1rc1 is installed but networkx==2.0 is required by {'spectra'}
```
(see https://travis-ci.org/ewels/MultiQC/builds/330352701)

I can fix this in my package, but it may be nice to relax the spectra requirements to just:

```
colormath>=3.0.0
```

Then more `colormath` versions will be tolerated, so there should be less chance of conflicts. I don't think you need the `networkx` line because `colormath` itself [will handle](https://github.com/gtaylor/python-colormath/blob/master/requirements.txt#L1) this dependency.

Suggestion only, I'd be interested to know what you think!

Cheers,

Phil

**Comment by jsvine** [comment]
I think that's a great idea. Changed in https://github.com/jsvine/spectra/commit/2269a0ae9b5923154b15bd661fb81179608f7ec2, and now available in `v0.0.11`. Thanks, Phil!

**Comment by ewels** [comment]
Awesome - thanks for the fast response and release!

**Comment by ewels** [comment]
Note - I finally got around to updating the conda-forge version to `v0.0.11`, so should be available through conda very soon: https://github.com/conda-forge/spectra-feedstock/pull/3

**Comment by jsvine** [comment]
Thanks!
