### ISSUE TITLE
converting rgb image into cmyk and vice versa?

### ISSUE THREAD

**Issue by K-M-Ibrahim-Khalilullah** [jsvine/spectra#16]
Thanks for the nice repo.
How can I convert rgb image into cmyk.
Again want to return rgb image

**Comment by jsvine** [comment]
Thanks, and hello. Although that might be hypothetically possible with this library, it is probably much easier with an image library such as PIL/Pillow: https://pillow.readthedocs.io/en/latest/handbook/tutorial.html#color-transforms
