### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by cameron-finn** [jsvine/spectra#2]
I got this error while going through the documentation.

/usr/local/lib/python3.4/dist-packages/spectra/core.py in range(self, count)
     99         distance = dom[-1] - dom[0]
    100         props = [ self(dom[0] + distance \* float(x)/(count-1))
--> 101             for x in xrange(count) ]
    102         return props

NameError: name 'xrange' is not defined

**Comment by jsvine** [comment]
Thanks for flagging, @cameron-finn! I goofed up on the python3 support. Should be fixed now, in v0.0.4: https://github.com/jsvine/spectra/commit/873f8b763cfa761d1d78886f5e65ecd3caabf5b6. Let me know if you run into any other bugs.
